# Generated by Django 4.1.3 on 2022-11-13 15:55

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='', storage=accounts.storage.OverwriteStorage(), upload_to='profiles')),
            ],
        ),
    ]
