# Generated by Django 4.0.3 on 2022-03-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='', upload_to='profiles'),
        ),
    ]
