# Generated by Django 4.1.3 on 2022-11-13 15:51

import attendance.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_user_image_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='', storage=attendance.storage.OverwriteStorage(), upload_to='profiles')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='', storage=attendance.storage.OverwriteStorage(), upload_to='user_uploaded'),
        ),
    ]
