# Generated by Django 4.1.3 on 2022-11-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_user1_alter_user_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
